### ISSUE TITLE
Prevent “In-Source Builds”

### ISSUE THREAD

**Issue by ClausKlein** [bemanproject/exemplar#67]
see too [Preventing “In-Source Builds”](https://discourse.cmake.org/t/preventing-in-source-builds/881)

**Comment by camio** [comment]
Per discussion [here](https://github.com/bemanproject/inplace_vector/pull/33#discussion_r1872448520), I don't think the complexity of preventing in-source builds is worth adding to our `CMakeLists.txt` files. I'm supportive if CMake itself were to prevent this somehow.
